/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Dashboard: () => import('#controllers/dashboard_controller'),
  Refresh: () => import('#controllers/refresh_controller'),
}
